package com.group5.gue.data.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data class for inserting a new annotation into the database.
 * This class excludes the 'id' and 'created' fields as they are automatically
 * generated by the database.
 *
 * @property building The building name where the annotation is being placed.
 * @property roomName The specific room identifier for the annotation.
 * @property level The floor level of the annotation's location.
 * @property latitude The geographical latitude coordinate.
 * @property longitude The geographical longitude coordinate.
 * @property creatorId The identifier of the user creating the annotation.
 */
@Serializable
data class AnnotationInsert(
    val building: String? = null,
    @SerialName("room_name")
    val roomName: String? = null,
    val level: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    @SerialName("creator_id")
    val creatorId: String? = null
)