sonar.projectKey=Lambertgec_App-dev-group-5
sonar.organization=appdevsonar-group5
sonar.host.url=https://sonarcloud.io
sonar.token=
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.coverage.exclusions=**/*Activity.kt,**/*Fragment.kt,**/databinding/*,**/BuildConfig.java
# Where the code lives
sonar.sources=app/src/main
# sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8